/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface RecBtn {
      'inverse': boolean;
      'large': boolean;
      'loading': boolean;
      'primary': boolean;
      'small': boolean;
    }
  }

  interface HTMLRecBtnElement extends StencilComponents.RecBtn, HTMLStencilElement {}

  var HTMLRecBtnElement: {
    prototype: HTMLRecBtnElement;
    new (): HTMLRecBtnElement;
  };
  interface HTMLElementTagNameMap {
    'rec-btn': HTMLRecBtnElement;
  }
  interface ElementTagNameMap {
    'rec-btn': HTMLRecBtnElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rec-btn': JSXElements.RecBtnAttributes;
    }
  }
  namespace JSXElements {
    export interface RecBtnAttributes extends HTMLAttributes {
      'inverse'?: boolean;
      'large'?: boolean;
      'loading'?: boolean;
      'primary'?: boolean;
      'small'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface RecH1 {

    }
  }

  interface HTMLRecH1Element extends StencilComponents.RecH1, HTMLStencilElement {}

  var HTMLRecH1Element: {
    prototype: HTMLRecH1Element;
    new (): HTMLRecH1Element;
  };
  interface HTMLElementTagNameMap {
    'rec-h1': HTMLRecH1Element;
  }
  interface ElementTagNameMap {
    'rec-h1': HTMLRecH1Element;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rec-h1': JSXElements.RecH1Attributes;
    }
  }
  namespace JSXElements {
    export interface RecH1Attributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
